version: '2'

volumes:
  esdata1:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    networks:
      - microblog
    environment:
        - xpack.security.enabled=false
        - cluster.name=elasticsearch
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
      - "9300:9300"

  microblog-rest-services:
    #build: ./target
    image: microblog-rest-services
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ENV_ARGS: ''
    networks:
      - microblog
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch

networks:
  microblog: